"""time

Revision ID: a816c8748a04
Revises: deb5f6e14a8e
Create Date: 2022-03-31 22:02:44.470700

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a816c8748a04'
down_revision = 'deb5f6e14a8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('updateAt', sa.DateTime(), nullable=True))
    op.drop_column('comment', 'upgradeAt')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('upgradeAt', sa.DATETIME(), nullable=True))
    op.drop_column('comment', 'updateAt')
    # ### end Alembic commands ###
